name: Deploy Hostinger FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Obter o código do repositório
      uses: actions/checkout@v4

    - name: ⚙️ Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 📦 Instalar dependências
      run: npm install

    - name: 🏗️ Fazer o Build do projeto
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    - name: 🚀 Sincronizar arquivos para a Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./dist/
        server-dir: /domains/auditorestcepe.org.br/public_html/
        dangerous-clean-slate: false
